apiVersion: batch/v1
kind: Job
metadata:
  name: port-scan-rr
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: port-scan
    spec:
      containers:
        - name: port-scan-rr
          image: 192.168.75.130:5000/port-scan-rr
      restartPolicy: OnFailure